[theme]
dark = "kanabox_transparent"
light = "edge_light_transparent"
fallback = "kanabox_transparent"

[editor]
line-number = "relative"
end-of-line-diagnostics = "hint"

[editor.file-picker]
hidden = false
git-ignore = true

[editor.inline-diagnostics]
cursor-line = "warning"
